### ISSUE TITLE
After running an action, the focus isn’t recalculated

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#111]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
When running an action, the focused item is not recalculated.

**To Reproduce**
1. Create two overlapping, interactive ESCitems
2. When clicking any of the items, make them invisible and non-interactive
3. Start the game and click the first item
4. Click again
=> Notice in the logs, that the now invisible and non-interactive item is still handled. It is still the focused item. If you move the mouse outside of the first item and back in, the second item can be clicked.

**Expected behavior**
The second item can be clicked instantly.

**Comment by dploeger** [comment]
I fixed it in a very hacky way by using this custom command with the item under the item that is made non-interactive:

```gdscript
# `update_tooltip target`
#
# Updates the tooltip as if the mouse has entered the target
# - target: global id of the target item
#
# @ESC
extends ESCBaseCommand
class_name UpdateTooltipCommand


# Return the descriptor of the arguments of this command
func configure() -> ESCCommandArgumentDescriptor:
	return ESCCommandArgumentDescriptor.new(
		1,
		[TYPE_STRING],
		[null]
	)


# Validate wether the given arguments match the command descriptor
func validate(arguments: Array):
	if not escoria.object_manager.has(arguments[0]):
		escoria.logger.report_errors(
			"update_tooltip: invalid global id",
			[
				"Object with global id %s not found" % [
					arguments[0],
				]
			]
		)
		return false

	return .validate(arguments)


# Run the command
func run(command_params: Array) -> int:
	var item = ((escoria.object_manager.get_object(command_params[0]) as ESCObject).node as ESCItem)
	for child in item.get_children():
		if child is CollisionPolygon2D:
			var mouse_local = item.get_viewport().get_mouse_position()
			var polygon = (child as CollisionPolygon2D).polygon

			if Geometry.is_point_in_polygon(mouse_local, polygon):
				item._on_mouse_entered()
				return ESCExecution.RC_OK
	escoria.main.current_scene.game.element_unfocused()
	return ESCExecution.RC_OK
```

**Comment by BHSDuncan** [comment]
@dploeger could you do me a favour and try this out again with the latest in `develop`? I only ask because a) we just committed a couple fixes that have to do with interactive and active items, and b) I'm not 100% sure I'm understanding/following your directions perfectly.

At your convenience, of course!

Thank you!

**Comment by dploeger** [comment]
Will do.

**Comment by dploeger** [comment]
The focus seems to be recalculated now, but afterwards the removed (and now non-interactive) item is still getting events and is not passing them through to the now visible element. I guess it's something about the hover stack.

**Comment by StraToN** [comment]
@balloonpopper 
1) and 2) fixed 
3) is normal as this is a trace debug that happens on every mouse input (including mouse movements) on the item. To avoid this log message, simply change debug level to DEBUG or lower.

**Comment by balloonpopper** [comment]
@StraToN Would you mind revisiting this ticket please? I've noticed a couple of things when retesting https://github.com/godot-escoria/escoria-issues/issues/312

1) With 9 verbs, every time you move your mouse off and on the active game window (assuming it's smaller than your monitor) this error appears
E 0:00:02.455   back: Can't take value from empty array.
  <C++ Error>   Condition "_p->array.size() == 0" is true. Returned: Variant()
  <C++ Source>  core/array.cpp:160 @ back()
  <Stack Trace> esc_inputs_manager.gd:188 @ unset_hovered_node()
                esc_item.gd:303 @ _on_mouse_exited()

2) If you have simplemouse enabled, you get the above error, as well as getting these errors when you quit
![image](https://user-images.githubusercontent.com/5151242/205473248-6ca6c629-27ec-4a60-b33f-ce4fab9b70c3.png)
These errors are from game.gd - function "_on_gamepad_disconnected" - line 123

**Comment by balloonpopper** [comment]
Rooms 18 and 19 don't work correctly currently. The tooltip isn't updated for either 9 verb or simplemouse - the items only "activate" under simplemouse, clicks are ignored in 9 verb.
